// Mocks generated by Mockito 5.4.6 from annotations
// in majunkita/test/features/manage_percas/domain/providers/perca_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:majunkita/features/manage_factories/data/models/factory_model.dart'
    as _i4;
import 'package:majunkita/features/manage_percas/data/models/perca_stock_model.dart'
    as _i7;
import 'package:majunkita/features/manage_percas/data/repositories/perca_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PercaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPercaRepository extends _i1.Mock implements _i2.PercaRepository {
  MockPercaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FactoryModel>> getFactoryList() =>
      (super.noSuchMethod(
            Invocation.method(#getFactoryList, []),
            returnValue: _i3.Future<List<_i4.FactoryModel>>.value(
              <_i4.FactoryModel>[],
            ),
          )
          as _i3.Future<List<_i4.FactoryModel>>);

  @override
  _i3.Future<String> uploadImageToStorage(_i5.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImageToStorage, [imageFile]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#uploadImageToStorage, [imageFile]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> saveStockToDatabase(_i7.PercasStock? stockData) =>
      (super.noSuchMethod(
            Invocation.method(#saveStockToDatabase, [stockData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveMultipleStocksToDatabase(
    List<_i7.PercasStock>? stockList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveMultipleStocksToDatabase, [stockList]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getPercaHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getPercaHistory, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);
}
