// Mocks generated by Mockito 5.4.6 from annotations
// in majunkita/test/features/manage_percas/domain/providers/perca_transactions_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:majunkita/features/manage_percas/data/repositories/perca_transactions_repository.dart'
    as _i2;
import 'package:majunkita/features/manage_tailors/data/models/tailor_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PercaTransactionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPercaTransactionsRepository extends _i1.Mock
    implements _i2.PercaTransactionsRepository {
  MockPercaTransactionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TailorModel>> getTailorList() =>
      (super.noSuchMethod(
            Invocation.method(#getTailorList, []),
            returnValue: _i3.Future<List<_i4.TailorModel>>.value(
              <_i4.TailorModel>[],
            ),
          )
          as _i3.Future<List<_i4.TailorModel>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAvailableSackSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableSackSummary, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> getAvailableSackCount(String? sackCode) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableSackCount, [sackCode]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, dynamic>> processTransactionBySackCode({
    required String? idTailor,
    required String? staffId,
    required String? sackCode,
    required int? sackCount,
    required DateTime? dateEntry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processTransactionBySackCode, [], {
              #idTailor: idTailor,
              #staffId: staffId,
              #sackCode: sackCode,
              #sackCount: sackCount,
              #dateEntry: dateEntry,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> processBulkTransactions({
    required String? idTailor,
    required String? staffId,
    required DateTime? dateEntry,
    required List<Map<String, dynamic>>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processBulkTransactions, [], {
              #idTailor: idTailor,
              #staffId: staffId,
              #dateEntry: dateEntry,
              #items: items,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getPercaTransactionHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getPercaTransactionHistory, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getTransactionsByTailor(
    String? tailorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByTailor, [tailorId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> getPercaTransactionById(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPercaTransactionById, [transactionId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> updatePercaTransaction(
    String? transactionId,
    Map<String, dynamic>? updateData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePercaTransaction, [
              transactionId,
              updateData,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePercaTransaction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePercaTransaction, [transactionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, double>> getMonthlyTransactionStats() =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyTransactionStats, []),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<Map<String, double>> getTotalWeightPerTailor() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalWeightPerTailor, []),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);
}
