// Mocks generated by Mockito 5.4.6 from annotations
// in majunkita/test/features/manage_factories/domain/providers/factory_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:majunkita/features/manage_factories/data/models/factory_model.dart'
    as _i2;
import 'package:majunkita/features/manage_factories/data/repositories/factory_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFactoryModel_0 extends _i1.SmartFake implements _i2.FactoryModel {
  _FakeFactoryModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FactoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFactoryRepository extends _i1.Mock implements _i3.FactoryRepository {
  MockFactoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.FactoryModel>> getAllFactories({
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllFactories, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.FactoryModel>>.value(
              <_i2.FactoryModel>[],
            ),
          )
          as _i4.Future<List<_i2.FactoryModel>>);

  @override
  _i4.Future<List<_i2.FactoryModel>> searchFactories(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFactories, [query]),
            returnValue: _i4.Future<List<_i2.FactoryModel>>.value(
              <_i2.FactoryModel>[],
            ),
          )
          as _i4.Future<List<_i2.FactoryModel>>);

  @override
  _i4.Future<_i2.FactoryModel?> getFactoryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFactoryById, [id]),
            returnValue: _i4.Future<_i2.FactoryModel?>.value(),
          )
          as _i4.Future<_i2.FactoryModel?>);

  @override
  _i4.Future<_i2.FactoryModel> createFactory({
    required String? factoryName,
    required String? address,
    required String? noTelp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createFactory, [], {
              #factoryName: factoryName,
              #address: address,
              #noTelp: noTelp,
            }),
            returnValue: _i4.Future<_i2.FactoryModel>.value(
              _FakeFactoryModel_0(
                this,
                Invocation.method(#createFactory, [], {
                  #factoryName: factoryName,
                  #address: address,
                  #noTelp: noTelp,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.FactoryModel>);

  @override
  _i4.Future<_i2.FactoryModel> updateFactory({
    required String? id,
    required String? factoryName,
    required String? address,
    required String? noTelp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFactory, [], {
              #id: id,
              #factoryName: factoryName,
              #address: address,
              #noTelp: noTelp,
            }),
            returnValue: _i4.Future<_i2.FactoryModel>.value(
              _FakeFactoryModel_0(
                this,
                Invocation.method(#updateFactory, [], {
                  #id: id,
                  #factoryName: factoryName,
                  #address: address,
                  #noTelp: noTelp,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.FactoryModel>);

  @override
  _i4.Future<void> deleteFactory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFactory, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getFactoryCount() =>
      (super.noSuchMethod(
            Invocation.method(#getFactoryCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
