-- ============================================================
-- MIGRATION: Fix WA Tambah Stok Perca — Two-Phase Architecture
-- Date: 2026-05-03
--
-- ROOT CAUSE:
--   Sama dengan pengambilan perca, Flutter melakukan insert satu
--   per satu untuk "tambah stok pabrik" untuk mengakali pg_sleep.
--   Akibatnya trigger terpisah di transaksi yang berbeda, dan pesan
--   gagal di-batch.
--
-- SOLUSI — Dua Fase:
--   Fase 1 (Trigger DB, otomatis):
--     Setiap INSERT percas_stock → trigger HANYA MENCATAT
--     transaksi ke staging table wa_percas_stock_pending_sessions.
--     Tidak ada WA yang dikirim dan TIDAK ADA pg_sleep.
--
--   Fase 2 (Eksplisit dari Flutter):
--     Flutter memanggil rpc_finalize_percas_stock_session(...)
--     → Kumpulkan semua row dari staging
--     → Buat satu pesan batch berisi semua karung
--     → Enqueue ke wa_notification_queue
--     → Bersihkan staging rows
-- ============================================================

-- ------------------------------------------------------------
-- 1. Staging table
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wa_percas_stock_pending_sessions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_key      TEXT NOT NULL,          -- factory_id|date
  factory_id       UUID NOT NULL REFERENCES public.factories(id) ON DELETE CASCADE,
  date_entry       DATE NOT NULL DEFAULT CURRENT_DATE,
  stock_id         UUID NOT NULL REFERENCES public.percas_stock(id) ON DELETE CASCADE,
  sack_code        TEXT,
  perca_type       TEXT,
  weight           NUMERIC,
  delivery_proof   TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.wa_percas_stock_pending_sessions IS
  'Staging satu-baris-per-karung untuk batching notifikasi WA tambah stok perca dari pabrik.';

CREATE INDEX IF NOT EXISTS idx_wa_percas_stock_pending_sessions_key
  ON public.wa_percas_stock_pending_sessions (session_key, created_at);

REVOKE ALL ON TABLE public.wa_percas_stock_pending_sessions FROM PUBLIC, anon, authenticated;
GRANT  ALL ON TABLE public.wa_percas_stock_pending_sessions TO service_role;


-- ------------------------------------------------------------
-- 2. Ganti trigger: HANYA CATAT ke staging
-- ------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_enqueue_wa_tambah_stok_perca ON public.percas_stock;

CREATE OR REPLACE FUNCTION public.trg_record_percas_stock_pending()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_key TEXT;
BEGIN
  v_session_key :=
    COALESCE(NEW.id_factory::TEXT, '-') || '|' ||
    COALESCE(NEW.date_entry::TEXT, '-');

  INSERT INTO public.wa_percas_stock_pending_sessions (
    session_key,
    factory_id,
    date_entry,
    stock_id,
    sack_code,
    perca_type,
    weight,
    delivery_proof
  ) VALUES (
    v_session_key,
    NEW.id_factory,
    NEW.date_entry,
    NEW.id,
    NEW.sack_code,
    NEW.perca_type,
    NEW.weight,
    NEW.delivery_proof
  );

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.trg_record_percas_stock_pending() IS
  'Trigger AFTER INSERT percas_stock: mencatat ke wa_percas_stock_pending_sessions tanpa sleep.';

CREATE TRIGGER trg_record_percas_stock_pending
  AFTER INSERT ON public.percas_stock
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_record_percas_stock_pending();


-- ------------------------------------------------------------
-- 3. RPC Finalisasi
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rpc_finalize_percas_stock_session(
  p_factory_id UUID,
  p_date_entry DATE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_key    TEXT;
  v_factory_name   TEXT;
  v_sack_count     INT := 0;
  v_total_weight   NUMERIC := 0;
  v_source_ids     UUID[] := '{}'::UUID[];
  v_details        TEXT := '';
  v_latest_stock_id UUID;
  v_image_url      TEXT;
  v_batch_key      TEXT;
  v_msg            TEXT;
  v_manager        RECORD;
  v_queue_ids      BIGINT[] := '{}'::BIGINT[];
  v_qid            BIGINT;
BEGIN
  v_session_key :=
    COALESCE(p_factory_id::TEXT, '-') || '|' ||
    COALESCE(p_date_entry::TEXT, '-');

  PERFORM pg_advisory_xact_lock(hashtextextended(v_session_key, 43));

  WITH deleted AS (
    DELETE FROM public.wa_percas_stock_pending_sessions
    WHERE session_key = v_session_key
    RETURNING stock_id, sack_code, perca_type, weight, delivery_proof, created_at
  )
  SELECT
    COUNT(*)::INT,
    COALESCE(SUM(weight), 0),
    array_agg(stock_id ORDER BY created_at ASC),
    string_agg(
      format(
        E'\u2022 %s | Jenis: %s | Berat: %s kg',
        COALESCE(sack_code, '-'),
        COALESCE(perca_type, '-'),
        COALESCE(weight, 0)::TEXT
      ),
      E'\n'
      ORDER BY created_at ASC
    ),
    (array_agg(stock_id ORDER BY created_at DESC))[1],
    -- Cari gambar delivery proof terakhir yang tidak kosong
    (array_agg(delivery_proof ORDER BY created_at DESC) FILTER (WHERE delivery_proof IS NOT NULL AND btrim(delivery_proof) <> ''))[1]
  INTO
    v_sack_count,
    v_total_weight,
    v_source_ids,
    v_details,
    v_latest_stock_id,
    v_image_url
  FROM deleted;

  IF COALESCE(v_sack_count, 0) = 0 THEN
    RETURN jsonb_build_object('sent', false, 'reason', 'no_pending_sacks');
  END IF;

  v_batch_key := md5(
    'percas_stock_final|' ||
    v_session_key || '|' ||
    COALESCE(array_to_string(v_source_ids, ','), '')
  );

  INSERT INTO public.wa_percas_stock_batches (
    batch_key,
    factory_id,
    date_entry,
    tx_count,
    total_weight,
    source_stock_ids,
    status
  )
  VALUES (
    v_batch_key,
    p_factory_id,
    p_date_entry,
    v_sack_count,
    v_total_weight,
    v_source_ids,
    'processing'
  )
  ON CONFLICT (batch_key) DO NOTHING;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('sent', false, 'reason', 'already_finalized');
  END IF;

  SELECT factory_name INTO v_factory_name
  FROM public.factories
  WHERE id = p_factory_id;

  v_msg := format(
    E'📦 *Stok Perca Baru*\n\nAsal Pabrik: %s\nTanggal: %s\nTotal Karung: %s\nTotal Berat: %s kg\n\n*Daftar Perca:*\n%s\n\nSilakan cek detail stok pada sistem.',
    COALESCE(v_factory_name, '-'),
    p_date_entry::TEXT,
    v_sack_count::TEXT,
    v_total_weight::TEXT,
    COALESCE(v_details, '-')
  );

  FOR v_manager IN
    SELECT p.no_telp
    FROM public.profiles p
    WHERE p.role::text = 'manager'
      AND p.no_telp IS NOT NULL
      AND btrim(p.no_telp) <> ''
  LOOP
    v_qid := public.enqueue_wa_notification(
      'tambah_stok_perca_grouped',
      'percas_stock',
      v_latest_stock_id,
      'manager',
      v_manager.no_telp,
      v_msg,
      v_image_url
    );
    IF v_qid IS NOT NULL THEN
      v_queue_ids := array_append(v_queue_ids, v_qid);
    END IF;
  END LOOP;

  UPDATE public.wa_percas_stock_batches
  SET
    status = 'sent',
    processed_at = now(),
    notification_queue_ids = v_queue_ids,
    last_error = NULL
  WHERE batch_key = v_batch_key;

  RETURN jsonb_build_object(
    'sent', true,
    'queue_ids', to_jsonb(v_queue_ids),
    'sack_count', v_sack_count
  );
EXCEPTION WHEN OTHERS THEN
  UPDATE public.wa_percas_stock_batches
  SET status = 'failed', processed_at = now(), last_error = SQLERRM
  WHERE batch_key = v_batch_key;
  RAISE;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.rpc_finalize_percas_stock_session(UUID, DATE) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.rpc_finalize_percas_stock_session(UUID, DATE) TO authenticated;
GRANT  EXECUTE ON FUNCTION public.rpc_finalize_percas_stock_session(UUID, DATE) TO service_role;

-- ------------------------------------------------------------
-- 4. Drop fungsi lama
-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS public.fn_enqueue_wa_percas_stock_grouped(UUID, DATE, INTEGER);
DROP FUNCTION IF EXISTS public.trg_enqueue_wa_tambah_stok_perca();
