-- ============================================================
-- MIGRATION: Group percas_stock WA notifications (idempotent)
-- Date: 2026-04-17
--
-- Tujuan:
--   Mengganti trigger WA per-row pada public.percas_stock (yang menyebabkan
--   multiple send) menjadi trigger grouped + idempotent per batch.
--
-- Hasil:
--   - 1 pesan WA manager per batch insert stok (dalam window waktu pendek)
--   - Isi pesan berisi daftar item: jenis perca + berat (+ sack code jika ada)
--   - Menyertakan 1 gambar representatif dari pabrik (delivery_proof)
--   - Hard idempotency via table guard + unique batch_key
-- ============================================================

-- ------------------------------------------------------------
-- 0) Drop trigger/function lama per-row jika ada
-- ------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_enqueue_wa_tambah_stok_perca ON public.percas_stock;

-- Function lama boleh tetap ada; namun kita replace di bawah agar aman.
-- CREATE OR REPLACE akan menimpa definisinya bila nama sama.

-- ------------------------------------------------------------
-- 1) Guard table idempotensi untuk batch stok perca
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wa_percas_stock_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_key TEXT NOT NULL UNIQUE,
  factory_id UUID NOT NULL,
  date_entry DATE NOT NULL,
  tx_count INTEGER NOT NULL DEFAULT 0,
  total_weight NUMERIC NOT NULL DEFAULT 0,
  source_stock_ids UUID[] NOT NULL DEFAULT '{}'::UUID[],
  status TEXT NOT NULL DEFAULT 'processing'
    CHECK (status IN ('processing', 'sent', 'failed')),
  notification_queue_ids BIGINT[] NOT NULL DEFAULT '{}'::BIGINT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  last_error TEXT
);

COMMENT ON TABLE public.wa_percas_stock_batches IS
  'Guard idempotensi notifikasi WA grouped untuk insert stok perca dari pabrik.';

COMMENT ON COLUMN public.wa_percas_stock_batches.batch_key IS
  'Kunci batch deterministik berbasis daftar stock id pada window waktu.';

CREATE INDEX IF NOT EXISTS idx_wa_percas_stock_batches_factory_date
  ON public.wa_percas_stock_batches (factory_id, date_entry, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_wa_percas_stock_batches_status
  ON public.wa_percas_stock_batches (status, created_at DESC);

REVOKE ALL ON TABLE public.wa_percas_stock_batches FROM PUBLIC, anon, authenticated;

-- ------------------------------------------------------------
-- 2) Worker function grouped + idempotent
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_enqueue_wa_percas_stock_grouped(
  p_factory_id UUID,
  p_date_entry DATE,
  p_time_window_seconds INTEGER DEFAULT 3
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_manager RECORD;
  v_factory_name TEXT;
  v_rows_count INTEGER := 0;
  v_total_weight NUMERIC := 0;
  v_details TEXT := '';
  v_image_url TEXT;
  v_batch_key TEXT;
  v_source_ids UUID[] := '{}'::UUID[];
  v_latest_stock_id UUID;
  v_queue_ids BIGINT[] := '{}'::BIGINT[];
  v_qid BIGINT;
  v_msg TEXT;
BEGIN
  SELECT f.factory_name
  INTO v_factory_name
  FROM public.factories f
  WHERE f.id = p_factory_id;

  -- Ambil item stok pada window waktu pendek agar satu batch jadi satu pesan
  WITH picked AS (
    SELECT
      ps.id,
      ps.perca_type,
      COALESCE(ps.weight, 0) AS weight,
      ps.sack_code,
      ps.delivery_proof,
      ps.created_at
    FROM public.percas_stock ps
    WHERE ps.id_factory = p_factory_id
      AND ps.date_entry = p_date_entry
      AND ps.created_at >= now() - make_interval(secs => GREATEST(COALESCE(p_time_window_seconds, 3), 1))
  ),
  agg AS (
    SELECT
      COUNT(*)::INT AS cnt,
      COALESCE(SUM(weight), 0) AS total_weight,
      string_agg(
        format(
          E'• %s | Jenis: %s | Berat: %s kg',
          COALESCE(sack_code, '-'),
          COALESCE(perca_type, '-'),
          COALESCE(weight, 0)::TEXT
        ),
        E'\n'
        ORDER BY created_at ASC
      ) AS details,
      array_agg(id ORDER BY created_at ASC) AS source_ids
    FROM picked
  )
  SELECT
    a.cnt,
    a.total_weight,
    COALESCE(a.details, ''),
    COALESCE(a.source_ids, '{}'::UUID[]),
    (
      SELECT ps2.id
      FROM public.percas_stock ps2
      WHERE ps2.id_factory = p_factory_id
        AND ps2.date_entry = p_date_entry
      ORDER BY ps2.created_at DESC
      LIMIT 1
    )
  INTO
    v_rows_count,
    v_total_weight,
    v_details,
    v_source_ids,
    v_latest_stock_id
  FROM agg a;

  IF COALESCE(v_rows_count, 0) = 0 THEN
    RETURN;
  END IF;

  -- Batch key deterministik untuk hard idempotency
  v_batch_key := md5(
    'percas_stock|' ||
    COALESCE(p_factory_id::TEXT, '-') || '|' ||
    COALESCE(p_date_entry::TEXT, '-') || '|' ||
    COALESCE(array_to_string(v_source_ids, ','), '')
  );

  INSERT INTO public.wa_percas_stock_batches (
    batch_key,
    factory_id,
    date_entry,
    tx_count,
    total_weight,
    source_stock_ids,
    status
  )
  VALUES (
    v_batch_key,
    p_factory_id,
    p_date_entry,
    v_rows_count,
    v_total_weight,
    v_source_ids,
    'processing'
  )
  ON CONFLICT (batch_key) DO NOTHING;

  -- Sudah/sedang diproses => stop (anti duplicate)
  IF NOT FOUND THEN
    RETURN;
  END IF;

  -- Ambil gambar representatif terbaru dari batch
  SELECT p.delivery_proof
  INTO v_image_url
  FROM (
    SELECT ps.delivery_proof, ps.created_at
    FROM public.percas_stock ps
    WHERE ps.id_factory = p_factory_id
      AND ps.date_entry = p_date_entry
      AND ps.created_at >= now() - make_interval(secs => GREATEST(COALESCE(p_time_window_seconds, 3), 1))
      AND ps.delivery_proof IS NOT NULL
      AND btrim(ps.delivery_proof) <> ''
    ORDER BY ps.created_at DESC
    LIMIT 1
  ) p;

  v_msg := format(
    E'📦 *Stok Perca Baru (Grouped)*\n\nAsal Pabrik: %s\nTanggal: %s\nTotal Karung: %s\nTotal Berat: %s kg\n\n*Daftar Perca:*\n%s\n\nSilakan cek detail stok pada sistem.',
    COALESCE(v_factory_name, '-'),
    p_date_entry::TEXT,
    v_rows_count::TEXT,
    COALESCE(v_total_weight, 0)::TEXT,
    v_details
  );

  -- Enqueue ke semua manager
  FOR v_manager IN
    SELECT p.no_telp
    FROM public.profiles p
    WHERE p.role::text = 'manager'
      AND p.no_telp IS NOT NULL
      AND btrim(p.no_telp) <> ''
  LOOP
    PERFORM public.enqueue_wa_notification(
      'tambah_stok_perca_grouped',
      'percas_stock',
      v_latest_stock_id,
      'manager',
      v_manager.no_telp,
      v_msg,
      v_image_url
    );

    -- Simpan queue id (best effort)
    SELECT q.id
    INTO v_qid
    FROM public.wa_notification_queue q
    WHERE q.event_type = 'tambah_stok_perca_grouped'
      AND q.source_table = 'percas_stock'
      AND q.source_id = v_latest_stock_id
      AND q.recipient_role = 'manager'
      AND q.message = v_msg
      AND COALESCE(q.image_url, '') = COALESCE(v_image_url, '')
    ORDER BY q.created_at DESC, q.id DESC
    LIMIT 1;

    IF v_qid IS NOT NULL THEN
      v_queue_ids := array_append(v_queue_ids, v_qid);
    END IF;
  END LOOP;

  UPDATE public.wa_percas_stock_batches b
  SET
    status = 'sent',
    processed_at = now(),
    notification_queue_ids = v_queue_ids,
    last_error = NULL
  WHERE b.batch_key = v_batch_key;

EXCEPTION WHEN OTHERS THEN
  UPDATE public.wa_percas_stock_batches b
  SET
    status = 'failed',
    processed_at = now(),
    last_error = SQLERRM
  WHERE b.batch_key = v_batch_key;

  RAISE;
END;
$$;

COMMENT ON FUNCTION public.fn_enqueue_wa_percas_stock_grouped(UUID, DATE, INTEGER) IS
  'Worker grouped + idempotent untuk enqueue WA stok perca baru ke manager.';

-- ------------------------------------------------------------
-- 3) Trigger function grouped (debounce + advisory lock)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_enqueue_wa_tambah_stok_perca()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lock_key BIGINT;
BEGIN
  -- lock per kombinasi pabrik + tanggal (mengurangi race duplicate)
  v_lock_key := hashtextextended(
    COALESCE(NEW.id_factory::TEXT, '-') || '|' ||
    COALESCE(NEW.date_entry::TEXT, '-'),
    0
  );

  IF pg_try_advisory_xact_lock(v_lock_key) THEN
    -- debounce singkat agar multi insert terkumpul
    PERFORM pg_sleep(2);

    PERFORM public.fn_enqueue_wa_percas_stock_grouped(
      NEW.id_factory,
      NEW.date_entry,
      4
    );
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.trg_enqueue_wa_tambah_stok_perca() IS
  'Trigger grouped untuk stok perca baru: 1 batch -> 1 notifikasi WA manager (idempotent).';

-- ------------------------------------------------------------
-- 4) Attach trigger baru
-- ------------------------------------------------------------
CREATE TRIGGER trg_enqueue_wa_tambah_stok_perca
  AFTER INSERT ON public.percas_stock
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_enqueue_wa_tambah_stok_perca();
