-- ============================================================
-- MIGRATION: WhatsApp Notification Queue Integration
-- Date: 2026-04-07
--
-- Adds:
--   1. Async queue + logs for WA API delivery attempts
--   2. Helper functions to normalize JID + enqueue notifications
--   3. Triggers for:
--      - majun_transactions  -> notify tailor
--      - percas_stock        -> notify manager
--      - expeditions         -> notify manager
--   4. dequeue_wa_notifications RPC for queue workers
-- ============================================================

CREATE TABLE IF NOT EXISTS public.wa_notification_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  source_table TEXT NOT NULL,
  source_id UUID NOT NULL,
  recipient_role TEXT NOT NULL,
  recipient_phone TEXT NOT NULL,
  message TEXT NOT NULL,
  image_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'sent', 'failed')),
  retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
  max_retries INTEGER NOT NULL DEFAULT 5 CHECK (max_retries > 0),
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ
);

COMMENT ON TABLE public.wa_notification_queue IS
  'Async queue for outbound WhatsApp notifications to go-whatsapp-web-multidevice.';

CREATE INDEX IF NOT EXISTS idx_wa_notification_queue_pending
  ON public.wa_notification_queue (status, next_attempt_at, created_at);

CREATE TABLE IF NOT EXISTS public.wa_notification_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_id BIGINT REFERENCES public.wa_notification_queue(id) ON DELETE SET NULL,
  endpoint TEXT NOT NULL,
  request_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  response_status INTEGER,
  response_body TEXT,
  success BOOLEAN NOT NULL,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.wa_notification_logs IS
  'Attempt logs for WA API calls to track delivery status and failures.';

CREATE OR REPLACE FUNCTION public.set_wa_notification_queue_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_wa_notification_queue_updated_at ON public.wa_notification_queue;
CREATE TRIGGER trg_wa_notification_queue_updated_at
  BEFORE UPDATE ON public.wa_notification_queue
  FOR EACH ROW
  EXECUTE FUNCTION public.set_wa_notification_queue_updated_at();

CREATE OR REPLACE FUNCTION public.normalize_wa_jid(p_phone TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_clean TEXT;
BEGIN
  IF p_phone IS NULL OR btrim(p_phone) = '' THEN
    RETURN NULL;
  END IF;

  IF right(lower(btrim(p_phone)), 15) = '@s.whatsapp.net' THEN
    RETURN lower(btrim(p_phone));
  END IF;

  v_clean := regexp_replace(p_phone, '[^0-9]', '', 'g');
  IF v_clean = '' THEN
    RETURN NULL;
  END IF;

  RETURN v_clean || '@s.whatsapp.net';
END;
$$;

CREATE OR REPLACE FUNCTION public.enqueue_wa_notification(
  p_event_type TEXT,
  p_source_table TEXT,
  p_source_id UUID,
  p_recipient_role TEXT,
  p_recipient_phone TEXT,
  p_message TEXT,
  p_image_url TEXT DEFAULT NULL
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_jid TEXT;
BEGIN
  v_jid := public.normalize_wa_jid(p_recipient_phone);

  IF v_jid IS NULL OR p_message IS NULL OR btrim(p_message) = '' THEN
    RETURN;
  END IF;

  INSERT INTO public.wa_notification_queue (
    event_type,
    source_table,
    source_id,
    recipient_role,
    recipient_phone,
    message,
    image_url
  ) VALUES (
    p_event_type,
    p_source_table,
    p_source_id,
    p_recipient_role,
    v_jid,
    p_message,
    NULLIF(btrim(p_image_url), '')
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_enqueue_wa_setor_majun()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tailor_name TEXT;
  v_tailor_phone TEXT;
BEGIN
  SELECT t.name, t.no_telp
  INTO v_tailor_name, v_tailor_phone
  FROM public.tailors t
  WHERE t.id = NEW.id_tailor;

  PERFORM public.enqueue_wa_notification(
    'setor_majun',
    'majun_transactions',
    NEW.id,
    'penjahit',
    v_tailor_phone,
    format(
      'Konfirmasi Setor Majun #%s. Penjahit: %s. Berat: %s kg. Upah: Rp%s.',
      NEW.id::text,
      COALESCE(v_tailor_name, '-'),
      NEW.weight_majun::text,
      NEW.earned_wage::text
    ),
    NEW.delivery_proof
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enqueue_wa_setor_majun ON public.majun_transactions;
CREATE TRIGGER trg_enqueue_wa_setor_majun
  AFTER INSERT ON public.majun_transactions
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_enqueue_wa_setor_majun();

CREATE OR REPLACE FUNCTION public.trg_enqueue_wa_tambah_stok_perca()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_manager RECORD;
  v_factory_name TEXT;
BEGIN
  SELECT f.factory_name
  INTO v_factory_name
  FROM public.factories f
  WHERE f.id = NEW.id_factory;

  FOR v_manager IN
    SELECT p.no_telp
    FROM public.profiles p
    WHERE p.role::text = 'manager'
      AND p.no_telp IS NOT NULL
      AND btrim(p.no_telp) <> ''
  LOOP
    PERFORM public.enqueue_wa_notification(
      'tambah_stok_perca',
      'percas_stock',
      NEW.id,
      'manager',
      v_manager.no_telp,
      format(
        'Stok perca baru dari %s. Jenis: %s. Berat: %s kg.',
        COALESCE(v_factory_name, '-'),
        NEW.perca_type,
        NEW.weight::text
      ),
      NEW.delivery_proof
    );
  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enqueue_wa_tambah_stok_perca ON public.percas_stock;
CREATE TRIGGER trg_enqueue_wa_tambah_stok_perca
  AFTER INSERT ON public.percas_stock
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_enqueue_wa_tambah_stok_perca();

CREATE OR REPLACE FUNCTION public.trg_enqueue_wa_expedition()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_manager RECORD;
BEGIN
  FOR v_manager IN
    SELECT p.no_telp
    FROM public.profiles p
    WHERE p.role::text = 'manager'
      AND p.no_telp IS NOT NULL
      AND btrim(p.no_telp) <> ''
  LOOP
    PERFORM public.enqueue_wa_notification(
      'expedition',
      'expeditions',
      NEW.id,
      'manager',
      v_manager.no_telp,
      format(
        'Status Pengiriman Majun #%s. Tujuan: %s. Karung: %s. Berat total: %s kg.',
        NEW.id::text,
        NEW.destination,
        NEW.sack_number::text,
        NEW.total_weight::text
      ),
      NEW.proof_of_delivery
    );
  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enqueue_wa_expedition ON public.expeditions;
CREATE TRIGGER trg_enqueue_wa_expedition
  AFTER INSERT ON public.expeditions
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_enqueue_wa_expedition();

CREATE OR REPLACE FUNCTION public.dequeue_wa_notifications(p_batch_size INTEGER DEFAULT 20)
RETURNS TABLE (
  id BIGINT,
  event_type TEXT,
  source_table TEXT,
  source_id UUID,
  recipient_role TEXT,
  recipient_phone TEXT,
  message TEXT,
  image_url TEXT,
  retry_count INTEGER,
  max_retries INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  WITH picked AS (
    SELECT q.id
    FROM public.wa_notification_queue q
    WHERE q.status = 'pending'
      AND q.next_attempt_at <= now()
      AND q.retry_count < q.max_retries
    ORDER BY q.created_at ASC
    LIMIT GREATEST(COALESCE(p_batch_size, 20), 1)
    FOR UPDATE SKIP LOCKED
  )
  UPDATE public.wa_notification_queue q
  SET status = 'processing'
  FROM picked
  WHERE q.id = picked.id
  RETURNING
    q.id,
    q.event_type,
    q.source_table,
    q.source_id,
    q.recipient_role,
    q.recipient_phone,
    q.message,
    q.image_url,
    q.retry_count,
    q.max_retries;
END;
$$;

REVOKE ALL ON TABLE public.wa_notification_queue FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.wa_notification_logs FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.dequeue_wa_notifications(INTEGER) FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.wa_notification_queue TO service_role;
GRANT ALL ON TABLE public.wa_notification_logs TO service_role;
GRANT EXECUTE ON FUNCTION public.dequeue_wa_notifications(INTEGER) TO service_role;
