-- ============================================================
-- MIGRATION: Add idempotent batch guard for WA perca-take trigger
-- Date: 2026-04-17
--
-- Tujuan:
--   Menambahkan mekanisme idempotensi berbasis "batch key" agar
--   notifikasi WhatsApp pengambilan perca tidak terkirim ganda.
--
-- Cakupan:
--   1) Tabel guard: public.wa_perca_take_batches
--   2) Revisi function worker:
--      public.fn_enqueue_wa_perca_take_grouped(...)
--      - hitung batch_key deterministik dari daftar transaksi pada window
--      - klaim batch (insert ON CONFLICT DO NOTHING)
--      - hanya sender pertama yang lanjut enqueue
--      - tandai status sent/failed + metadata queue ids
--
-- Catatan:
--   - Function trigger existing `public.trg_enqueue_wa_perca_take()` tetap dipakai.
--   - Migration ini aman dijalankan berulang (IF NOT EXISTS / OR REPLACE).
-- ============================================================

-- ------------------------------------------------------------
-- 1) Guard table untuk idempotensi batch pengambilan perca
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wa_perca_take_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_key TEXT NOT NULL UNIQUE,
  tailor_id UUID NOT NULL,
  staff_id UUID,
  date_entry DATE NOT NULL,
  tx_count INTEGER NOT NULL DEFAULT 0,
  total_weight NUMERIC NOT NULL DEFAULT 0,
  source_transaction_ids UUID[] NOT NULL DEFAULT '{}'::UUID[],
  status TEXT NOT NULL DEFAULT 'processing'
    CHECK (status IN ('processing', 'sent', 'failed')),
  notification_queue_ids BIGINT[] NOT NULL DEFAULT '{}'::BIGINT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  last_error TEXT
);

COMMENT ON TABLE public.wa_perca_take_batches IS
  'Guard idempotensi notifikasi WA pengambilan perca per batch transaksi.';

COMMENT ON COLUMN public.wa_perca_take_batches.batch_key IS
  'Kunci batch deterministik berbasis transaksi yang terpilih dalam time window.';

CREATE INDEX IF NOT EXISTS idx_wa_perca_take_batches_tailor_date
  ON public.wa_perca_take_batches (tailor_id, date_entry, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_wa_perca_take_batches_status
  ON public.wa_perca_take_batches (status, created_at DESC);

REVOKE ALL ON TABLE public.wa_perca_take_batches FROM PUBLIC, anon, authenticated;

-- ------------------------------------------------------------
-- 2) Revisi worker function dengan hard idempotency
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_enqueue_wa_perca_take_grouped(
  p_tailor_id UUID,
  p_staff_id UUID,
  p_date_entry DATE,
  p_time_window_seconds INTEGER DEFAULT 2
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_manager RECORD;
  v_tailor_name TEXT;
  v_rows_count INTEGER := 0;
  v_total_weight NUMERIC := 0;
  v_details TEXT := '';
  v_image_url TEXT;
  v_batch_key TEXT;
  v_source_ids UUID[] := '{}'::UUID[];
  v_latest_tx_id UUID;
  v_queue_ids BIGINT[] := '{}'::BIGINT[];
  v_qid BIGINT;
  v_msg TEXT;
BEGIN
  -- Nama penjahit
  SELECT t.name
  INTO v_tailor_name
  FROM public.tailors t
  WHERE t.id = p_tailor_id;

  -- Ambil seluruh row transaksi dalam jendela waktu agar 1 batch jadi 1 pesan
  WITH picked AS (
    SELECT
      pt.id,
      pt.id_stock_perca,
      COALESCE(pt.percas_type, ps.perca_type, '-') AS perca_type,
      COALESCE(pt.weight, ps.weight, 0) AS weight,
      ps.sack_code,
      ps.delivery_proof,
      pt.created_at
    FROM public.perca_transactions pt
    LEFT JOIN public.percas_stock ps
      ON ps.id = pt.id_stock_perca
    WHERE pt.id_tailors = p_tailor_id
      AND COALESCE(pt.staff_id, p_staff_id) = p_staff_id
      AND pt.date_entry = p_date_entry
      AND pt.created_at >= now() - make_interval(secs => GREATEST(COALESCE(p_time_window_seconds, 2), 1))
  ),
  agg AS (
    SELECT
      COUNT(*)::INT AS cnt,
      COALESCE(SUM(weight), 0) AS total_weight,
      string_agg(
        format(
          E'• %s | Jenis: %s | Berat: %s kg',
          COALESCE(sack_code, '-'),
          COALESCE(perca_type, '-'),
          COALESCE(weight, 0)::TEXT
        ),
        E'\n'
        ORDER BY created_at ASC
      ) AS details,
      array_agg(id ORDER BY created_at ASC) AS source_ids,
      max(created_at) AS max_created_at
    FROM picked
  )
  SELECT
    a.cnt,
    a.total_weight,
    COALESCE(a.details, ''),
    COALESCE(a.source_ids, '{}'::UUID[]),
    (
      SELECT pt2.id
      FROM public.perca_transactions pt2
      WHERE pt2.id_tailors = p_tailor_id
        AND COALESCE(pt2.staff_id, p_staff_id) = p_staff_id
        AND pt2.date_entry = p_date_entry
      ORDER BY pt2.created_at DESC
      LIMIT 1
    )
  INTO
    v_rows_count,
    v_total_weight,
    v_details,
    v_source_ids,
    v_latest_tx_id
  FROM agg a;

  -- Jika tidak ada data terpilih, hentikan
  IF COALESCE(v_rows_count, 0) = 0 THEN
    RETURN;
  END IF;

  -- Batch key deterministik (berbasis daftar transaction id pada batch)
  -- format: perca_take|tailor|staff|date|id1,id2,id3
  v_batch_key := md5(
    'perca_take|' ||
    COALESCE(p_tailor_id::TEXT, '-') || '|' ||
    COALESCE(p_staff_id::TEXT, '-') || '|' ||
    COALESCE(p_date_entry::TEXT, '-') || '|' ||
    COALESCE(array_to_string(v_source_ids, ','), '')
  );

  -- Klaim batch key (idempotency hard guard)
  INSERT INTO public.wa_perca_take_batches (
    batch_key,
    tailor_id,
    staff_id,
    date_entry,
    tx_count,
    total_weight,
    source_transaction_ids,
    status
  )
  VALUES (
    v_batch_key,
    p_tailor_id,
    p_staff_id,
    p_date_entry,
    v_rows_count,
    v_total_weight,
    v_source_ids,
    'processing'
  )
  ON CONFLICT (batch_key) DO NOTHING;

  -- Jika tidak dapat claim, artinya batch sudah/sedang diproses => stop
  IF NOT FOUND THEN
    RETURN;
  END IF;

  -- Ambil satu gambar pabrik representatif dari batch (delivery_proof terbaru)
  SELECT p.delivery_proof
  INTO v_image_url
  FROM (
    SELECT
      ps.delivery_proof,
      pt.created_at
    FROM public.perca_transactions pt
    LEFT JOIN public.percas_stock ps
      ON ps.id = pt.id_stock_perca
    WHERE pt.id_tailors = p_tailor_id
      AND COALESCE(pt.staff_id, p_staff_id) = p_staff_id
      AND pt.date_entry = p_date_entry
      AND pt.created_at >= now() - make_interval(secs => GREATEST(COALESCE(p_time_window_seconds, 2), 1))
      AND ps.delivery_proof IS NOT NULL
      AND btrim(ps.delivery_proof) <> ''
    ORDER BY pt.created_at DESC
    LIMIT 1
  ) p;

  v_msg := format(
    E'📥 *Pengambilan Perca dari Pabrik*\n\nTanggal: %s\nPenjahit: %s\nTotal Karung: %s\nTotal Berat: %s kg\n\n*Daftar Karung/Perca:*\n%s\n\nSilakan cek detail transaksi pada sistem.',
    p_date_entry::TEXT,
    COALESCE(v_tailor_name, '-'),
    v_rows_count::TEXT,
    COALESCE(v_total_weight, 0)::TEXT,
    v_details
  );

  -- Kirim ke semua manager (enqueue ke queue)
  FOR v_manager IN
    SELECT p.no_telp
    FROM public.profiles p
    WHERE p.role::text = 'manager'
      AND p.no_telp IS NOT NULL
      AND btrim(p.no_telp) <> ''
  LOOP
    -- Enqueue
    PERFORM public.enqueue_wa_notification(
      'pengambilan_perca',
      'perca_transactions',
      v_latest_tx_id,
      'manager',
      v_manager.no_telp,
      v_msg,
      v_image_url
    );

    -- Ambil id queue terakhir yang matching (best effort)
    SELECT q.id
    INTO v_qid
    FROM public.wa_notification_queue q
    WHERE q.event_type = 'pengambilan_perca'
      AND q.source_table = 'perca_transactions'
      AND q.source_id = v_latest_tx_id
      AND q.recipient_role = 'manager'
      AND q.message = v_msg
      AND COALESCE(q.image_url, '') = COALESCE(v_image_url, '')
    ORDER BY q.created_at DESC, q.id DESC
    LIMIT 1;

    IF v_qid IS NOT NULL THEN
      v_queue_ids := array_append(v_queue_ids, v_qid);
    END IF;
  END LOOP;

  -- Tandai sukses
  UPDATE public.wa_perca_take_batches b
  SET
    status = 'sent',
    processed_at = now(),
    notification_queue_ids = v_queue_ids,
    last_error = NULL
  WHERE b.batch_key = v_batch_key;

EXCEPTION WHEN OTHERS THEN
  -- Tandai gagal + simpan error
  UPDATE public.wa_perca_take_batches b
  SET
    status = 'failed',
    processed_at = now(),
    last_error = SQLERRM
  WHERE b.batch_key = v_batch_key;

  RAISE;
END;
$$;

COMMENT ON FUNCTION public.fn_enqueue_wa_perca_take_grouped(UUID, UUID, DATE, INTEGER) IS
  'Worker WA pengambilan perca dengan guard idempotensi batch_key agar tidak duplicate send.';
