-- ============================================================
-- MIGRATION: Fix WA Perca-Take — Two-Phase Architecture
-- Date: 2026-05-03
--
-- ROOT CAUSE:
--   Flutter memanggil processTransaction() per karung secara
--   sequential (masing-masing HTTP call = transaksi DB terpisah).
--   Ketika trigger karung-1 bangun dari pg_sleep(2), karung-2
--   belum di-INSERT karena Flutter baru mengirimnya setelah
--   karung-1 selesai. Tidak ada time-window yang bisa menangkap
--   semua karung karena masing-masing tiba dalam transaksi DB
--   yang berbeda dan berurutan.
--
-- SOLUSI — Dua Fase:
--   Fase 1 (Trigger DB, otomatis):
--     Setiap INSERT perca_transactions → trigger HANYA MENCATAT
--     transaksi ke staging table wa_perca_pending_sessions.
--     Tidak ada WA yang dikirim di sini.
--
--   Fase 2 (Eksplisit dari Flutter, setelah semua karung selesai):
--     Flutter memanggil rpc_finalize_perca_take_session(...)
--     → Kumpulkan semua row dari staging untuk tailor+date+session
--     → Buat satu pesan batch berisi semua karung
--     → Enqueue ke wa_notification_queue
--     → Bersihkan staging rows
--
-- Perubahan:
--   1. Buat tabel wa_perca_pending_sessions (staging per-sack)
--   2. Ganti trigger: tidak kirim WA, hanya insert ke staging
--   3. Buat RPC rpc_finalize_perca_take_session (dipanggil Flutter)
--   4. Drop fungsi lama yang berbasis time-window
-- ============================================================


-- ============================================================
-- 1. Staging table: satu row per karung yang menunggu dikirim
-- ============================================================
CREATE TABLE IF NOT EXISTS public.wa_perca_pending_sessions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_key      TEXT NOT NULL,          -- tailor_id|staff_id|date (group key)
  tailor_id        UUID NOT NULL REFERENCES public.tailors(id) ON DELETE CASCADE,
  staff_id         UUID,
  date_entry       DATE NOT NULL DEFAULT CURRENT_DATE,
  perca_tx_id      UUID NOT NULL REFERENCES public.perca_transactions(id) ON DELETE CASCADE,
  sack_code        TEXT,
  perca_type       TEXT,
  weight           NUMERIC,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.wa_perca_pending_sessions IS
  'Staging satu-baris-per-karung untuk batching notifikasi WA pengambilan perca.
   Baris diinsert oleh trigger, lalu dibaca + dihapus oleh rpc_finalize_perca_take_session.';

CREATE INDEX IF NOT EXISTS idx_wa_perca_pending_sessions_key
  ON public.wa_perca_pending_sessions (session_key, created_at);

CREATE INDEX IF NOT EXISTS idx_wa_perca_pending_sessions_tailor_date
  ON public.wa_perca_pending_sessions (tailor_id, date_entry, staff_id);

-- Hanya service_role yang boleh akses
REVOKE ALL ON TABLE public.wa_perca_pending_sessions FROM PUBLIC, anon, authenticated;
GRANT  ALL ON TABLE public.wa_perca_pending_sessions TO service_role;


-- ============================================================
-- 2. Ganti trigger: HANYA CATAT ke staging, tidak kirim WA
-- ============================================================

-- Drop trigger lama
DROP TRIGGER IF EXISTS trg_enqueue_wa_perca_take ON public.perca_transactions;

-- Fungsi trigger baru: cepat, tidak ada pg_sleep, tidak ada WA
CREATE OR REPLACE FUNCTION public.trg_record_perca_take_pending()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sack_code  TEXT;
  v_perca_type TEXT;
  v_weight     NUMERIC;
  v_session_key TEXT;
BEGIN
  -- Ambil detail dari percas_stock (best effort, boleh NULL)
  SELECT
    ps.sack_code,
    COALESCE(NEW.percas_type, ps.perca_type, '-'),
    COALESCE(NEW.weight, ps.weight, 0)
  INTO v_sack_code, v_perca_type, v_weight
  FROM public.percas_stock ps
  WHERE ps.id = NEW.id_stock_perca;

  -- session_key = tailor_id|staff_id|date (group key untuk finalisasi)
  v_session_key :=
    COALESCE(NEW.id_tailors::TEXT, '-') || '|' ||
    COALESCE(NEW.staff_id::TEXT,   '-') || '|' ||
    COALESCE(NEW.date_entry::TEXT, '-');

  -- Insert ke staging (fire-and-forget, tidak memblokir commit utama)
  INSERT INTO public.wa_perca_pending_sessions (
    session_key,
    tailor_id,
    staff_id,
    date_entry,
    perca_tx_id,
    sack_code,
    perca_type,
    weight
  ) VALUES (
    v_session_key,
    NEW.id_tailors,
    NEW.staff_id,
    NEW.date_entry,
    NEW.id,
    v_sack_code,
    v_perca_type,
    v_weight
  );

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.trg_record_perca_take_pending() IS
  'Trigger AFTER INSERT perca_transactions: mencatat satu baris ke wa_perca_pending_sessions.
   Tidak ada WA yang dikirim di sini. Panggil rpc_finalize_perca_take_session dari Flutter.';

-- Attach trigger baru (row-level, ringan, tanpa sleep)
CREATE TRIGGER trg_record_perca_take_pending
  AFTER INSERT ON public.perca_transactions
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_record_perca_take_pending();


-- ============================================================
-- 3. RPC Finalisasi — dipanggil SATU KALI oleh Flutter
--    setelah semua karung dalam sesi berhasil diinsert
-- ============================================================

CREATE OR REPLACE FUNCTION public.rpc_finalize_perca_take_session(
  p_tailor_id  UUID,
  p_staff_id   UUID,
  p_date_entry DATE
)
RETURNS JSONB   -- { "sent": true/false, "queue_ids": [...], "sack_count": N }
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_key    TEXT;
  v_tailor_name    TEXT;
  v_tailor_phone   TEXT;
  v_rows           RECORD;
  v_details        TEXT := '';
  v_total_weight   NUMERIC := 0;
  v_sack_count     INT := 0;
  v_latest_tx_id   UUID;
  v_msg            TEXT;
  v_manager        RECORD;
  v_queue_ids      BIGINT[] := '{}'::BIGINT[];
  v_qid            BIGINT;
  v_batch_key      TEXT;
  v_source_ids     UUID[] := '{}'::UUID[];
BEGIN
  v_session_key :=
    COALESCE(p_tailor_id::TEXT, '-') || '|' ||
    COALESCE(p_staff_id::TEXT,  '-') || '|' ||
    COALESCE(p_date_entry::TEXT,'-');

  -- Kunci session agar tidak ada dua finalisasi paralel
  -- (advisory lock berbasis session key, bukan xact)
  PERFORM pg_advisory_xact_lock(
    hashtextextended(v_session_key, 42)
  );

  -- Ambil semua sacks yang pending untuk session ini
  -- (DELETE ... RETURNING agar atomic: baca + hapus sekaligus)
  WITH deleted AS (
    DELETE FROM public.wa_perca_pending_sessions
    WHERE session_key = v_session_key
    RETURNING perca_tx_id, sack_code, perca_type, weight, created_at
  )
  SELECT
    COUNT(*)::INT,
    COALESCE(SUM(weight), 0),
    array_agg(perca_tx_id ORDER BY created_at ASC),
    -- Susun detail baris per karung
    string_agg(
      format(
        E'\u2022 %s | Jenis: %s | Berat: %s kg',
        COALESCE(sack_code, '-'),
        COALESCE(perca_type, '-'),
        COALESCE(weight, 0)::TEXT
      ),
      E'\n'
      ORDER BY created_at ASC
    ),
    -- latest tx id untuk source_id di wa_notification_queue
    (array_agg(perca_tx_id ORDER BY created_at DESC))[1]
  INTO
    v_sack_count,
    v_total_weight,
    v_source_ids,
    v_details,
    v_latest_tx_id
  FROM deleted;

  -- Tidak ada sacks yang pending → tidak ada yang dikirim
  IF COALESCE(v_sack_count, 0) = 0 THEN
    RETURN jsonb_build_object(
      'sent',       false,
      'reason',     'no_pending_sacks',
      'queue_ids',  '[]'::jsonb,
      'sack_count', 0
    );
  END IF;

  -- Batch key deterministik untuk guard idempotency
  v_batch_key := md5(
    'perca_take_final|' ||
    v_session_key || '|' ||
    COALESCE(array_to_string(v_source_ids, ','), '')
  );

  -- Guard idempotency: jika sudah pernah dikirim, skip
  INSERT INTO public.wa_perca_take_batches (
    batch_key,
    tailor_id,
    staff_id,
    date_entry,
    tx_count,
    total_weight,
    source_transaction_ids,
    status
  )
  VALUES (
    v_batch_key,
    p_tailor_id,
    p_staff_id,
    p_date_entry,
    v_sack_count,
    v_total_weight,
    v_source_ids,
    'processing'
  )
  ON CONFLICT (batch_key) DO NOTHING;

  IF NOT FOUND THEN
    -- Sudah pernah difinalisasi
    RETURN jsonb_build_object(
      'sent',       false,
      'reason',     'already_finalized',
      'queue_ids',  '[]'::jsonb,
      'sack_count', v_sack_count
    );
  END IF;

  -- Ambil identitas penjahit
  SELECT t.name, t.no_telp
  INTO   v_tailor_name, v_tailor_phone
  FROM   public.tailors t
  WHERE  t.id = p_tailor_id;

  -- Susun pesan batch (SATU pesan untuk semua karung)
  v_msg := format(
    E'📥 *Pengambilan Perca*\n\nTanggal: %s\nPenjahit: %s\nTotal Karung: %s\nTotal Berat: %s kg\n\n*Daftar Karung/Perca:*\n%s\n\nSilakan cek detail transaksi pada sistem.',
    p_date_entry::TEXT,
    COALESCE(v_tailor_name, '-'),
    v_sack_count::TEXT,
    v_total_weight::TEXT,
    COALESCE(v_details, '-')
  );

  -- Kirim ke penjahit (Fix 2: gunakan RETURNS BIGINT langsung)
  IF v_tailor_phone IS NOT NULL AND btrim(v_tailor_phone) <> '' THEN
    v_qid := public.enqueue_wa_notification(
      'pengambilan_perca',
      'perca_transactions',
      v_latest_tx_id,
      'penjahit',
      v_tailor_phone,
      v_msg
    );
    IF v_qid IS NOT NULL THEN
      v_queue_ids := array_append(v_queue_ids, v_qid);
    END IF;
  END IF;

  -- Kirim ke semua manager
  FOR v_manager IN
    SELECT p.no_telp
    FROM   public.profiles p
    WHERE  p.role::text = 'manager'
      AND  p.no_telp IS NOT NULL
      AND  btrim(p.no_telp) <> ''
  LOOP
    v_qid := public.enqueue_wa_notification(
      'pengambilan_perca',
      'perca_transactions',
      v_latest_tx_id,
      'manager',
      v_manager.no_telp,
      v_msg
    );
    IF v_qid IS NOT NULL THEN
      v_queue_ids := array_append(v_queue_ids, v_qid);
    END IF;
  END LOOP;

  -- Tandai batch sukses
  UPDATE public.wa_perca_take_batches
  SET
    status                 = 'sent',
    processed_at           = now(),
    notification_queue_ids = v_queue_ids,
    last_error             = NULL
  WHERE batch_key = v_batch_key;

  RETURN jsonb_build_object(
    'sent',       true,
    'queue_ids',  to_jsonb(v_queue_ids),
    'sack_count', v_sack_count
  );

EXCEPTION WHEN OTHERS THEN
  -- Tandai batch gagal
  UPDATE public.wa_perca_take_batches
  SET
    status       = 'failed',
    processed_at = now(),
    last_error   = SQLERRM
  WHERE batch_key = v_batch_key;

  RAISE;
END;
$$;

COMMENT ON FUNCTION public.rpc_finalize_perca_take_session(UUID, UUID, DATE) IS
  'Dipanggil SATU KALI oleh Flutter setelah semua karung berhasil diinsert.
   Membaca + menghapus staging wa_perca_pending_sessions, menyusun SATU pesan batch,
   lalu mengirim ke penjahit dan semua manager via wa_notification_queue.
   Returns JSONB: { sent, queue_ids, sack_count }.';

-- Hanya authenticated yang boleh memanggil (admin/staff)
REVOKE EXECUTE ON FUNCTION public.rpc_finalize_perca_take_session(UUID, UUID, DATE) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.rpc_finalize_perca_take_session(UUID, UUID, DATE) TO authenticated;
GRANT  EXECUTE ON FUNCTION public.rpc_finalize_perca_take_session(UUID, UUID, DATE) TO service_role;


-- ============================================================
-- 4. Drop fungsi lama yang berbasis time-window
--    (tidak dipakai lagi — digantikan oleh arsitektur dua-fase)
-- ============================================================
DROP FUNCTION IF EXISTS public.fn_enqueue_wa_perca_take_grouped(UUID, UUID, DATE, INTEGER);
DROP FUNCTION IF EXISTS public.trg_enqueue_wa_perca_take();
